### ISSUE TITLE
[BUG] BackEnd: Error Invalid Status Code

### ISSUE THREAD

**Issue by ReyRizki** [d4a-jtk19-webdev/proyek3-reproduce#20]
**Deskripsi**
Ketika melakukan query terhadap dosen yang mengajar mata kuliah, terdapat error dengan message tertera di bagian Screenshots. Hal ini kemungkinan disebabkan oleh penggunaan many-to-many relationship di dalam association. Kemungkinan juga association lain yang belum diketahui dapat terdampak error yang sama.

**Cara Reproduce**
Langkah-langkah untuk menemukan bug yang sama:
1. Jalankan proyek sesuai dengan dokumentasi
2. Login aplikasi kemudian buka ke halaman monitoring
3. Periksa console di bagian service-monitoring
4. Atau bisa juga lakukan pemanggilan API di API Client dengan URL `http://localhost:5001/monitoring/dosen/kelas/196009281994031000`

**Ekspektasi**
API berjalan dan memberikan response yang sesuai.

**Screenshots**
![image](https://user-images.githubusercontent.com/39304683/146677449-78238fa5-d63f-4498-9e9f-c7d4f7a56798.png)

**Environment**
 - OS: FerenOS 2021.10
 - Browser: Brave 1.30.80
 - API Client: Thunder Client 1.9.1

**Cara Perbaikan yang sudah Dicoba**
Belum ada percobaan, akan tetapi sudah diketahui perbaikan dapat dilakukan dengan cara mengatur query yang digunakan. Caranya mirip dengan ketika membuat API untuk mendapatkan jabatan dosen berdasarkan NIP

**Comment by fauh45** [comment]
Error kelihatannya bukan di sequelized relationship tapi dengan controller. Will look into it.

**Comment by fauh45** [comment]
Root cause found. [Line 41 of Kelas controller](https://github.com/d4a-jtk19-webdev/proyek-webdev-d4a-2021/blob/main/service-monitoring/src/controller/Kelas.js#L39) have error handler, such on error it will responded with the error code of the error object.

```js
res.status(error.status).json({ error })
```

Problem is, `error` object does not always have any `status` attribute inside it. There are 2 ways to resolve this, throw the error so that it will got catched by global error middleware in `server.js`, or change the line into,

```js
res.status(error.status || 500).json({ error })
```

For quick and easy fix. Would recommend the latter as it is easier, and we don't have many time left anyway lol

**Comment by fauh45** [comment]
Solved by a commit to `main` (WHY?) https://github.com/d4a-jtk19-webdev/proyek-webdev-d4a-2021/commit/3da0df2b19d05f62a47a9b760cc9186f564081ee

**Comment by fauh45** [comment]
Backend returns 500, but turns out doesn't work properly. Caused by wrong association config.

**Comment by fauh45** [comment]
Should be fixed now!
